### ISSUE TITLE
Project4代码于效果gif有区别

### ISSUE THREAD

**Issue by karson711** [allenwong/30DaysofSwift#15]
Project4的代码只实现了scrollVIew滑动，希望大神能提供实现效果图的代码！

**Comment by allenwong** [comment]
抱歉传错了项目代码，你是第一个发现的，谢谢，我已经传了正确的项目代码进去，你看看：
https://github.com/allenwong/30DaysofSwift/tree/master/Project%2004%20-%20SnapChatMenu

**Comment by allenwong** [comment]
我还是个初学者，还不是什么大神呢:)
