### ISSUE TITLE
Project 1 Button Property

### ISSUE THREAD

**Issue by JialiDu** [allenwong/30DaysofSwift#28]
project 1 里面的button的属性设置成hidden的话，应该是会不显示吧。和demo效果应该是不一样的吧。感觉和demo效果一样的话应该用enable吧

**Comment by leeguoyu** [comment]
我也是晕了好久，在想为什么用Allen用的是hidden但是实际按钮并不会hidden呢？仔细一看storyboard原来是在hidden之后的按钮下面还放了两个按钮。其实用.enabled 的true或false就行了。

**Comment by allenwong** [comment]
谢谢两位，这是我第一个项目，那个时候经验不对，我一会儿 fix

**Comment by allenwong** [comment]
Fixed it.
