### ISSUE TITLE
Project10，show segue to "View Controller" not work

### ISSUE THREAD

**Issue by CaliosD** [allenwong/30DaysofSwift#30]
When login button is pressed, nothing happens, which is expected to show another welcome view controller. Hope you could fix it some time.

PS: I recommend you to group source files from https://github.com/movielala/VideoSplashKit into a folder or so, to show that it's a bundle, instead of files created by your own. Just a suggestion. :)

**Comment by CaliosD** [comment]
I found the solution by myself.
After comparing your usage of `VideoSplashViewController` and the original demo, I found that you added `view.userInteractionEnabled = false` at last line of function `setupVideoBackground`. Annotate it, and everything is OK.

Then I realized that you may just wanna forbid users to present another view controller... So, I just close it myself.

PS: Like your project so much, and appreciate your hard work. :+1:

**Comment by allenwong** [comment]
Thanks a lot @CaliosD , I do really appreciate my project is good for you. 
It's just an useless button, the main function is show how to put a video as the background in splash screen.😂
