### ISSUE TITLE
Project 01 为什么要使用 CoreData?

### ISSUE THREAD

**Issue by nswbmw** [allenwong/30DaysofSwift#34]
rt，AppDelegate 中不少有关 CoreData 的代码，尝试去掉也能运行，那第一个简单的 demo 为什么要使用 CoreData 呢？意义何在？

**Comment by nswbmw** [comment]
e..其他project也用到了..

**Comment by zcill** [comment]
@nswbmw 作者应该是在建Xcode工程的时候，把那个启用CoreDate选项勾选了

**Comment by allenwong** [comment]
不好意思，打上勾了。

**Comment by nswbmw** [comment]
@allenwong  e..如果没用到就去掉吧? 否则可能会引起一些新手（比如我）的疑惑 :)
