### ISSUE TITLE
[Question] How to integrate SlideOutMenu into an existing app

### ISSUE THREAD

**Issue by PanosSakkos** [allenwong/30DaysofSwift#41]
Hi there, *excellent* repository! :clap: 

I would love to add your slide out menu in my [app](https://dono-app.github.io/), but I've struggled with it so far. The app consists of a storyboard with a navigation controller and 3 views and I want to add your slide out menu in order to point to these three views. Would you like to give me a few pointers on how to do it?

Keep up the good work! :clap: 

Best,
:panos

**Comment by allenwong** [comment]
I imported this project into mine, you do it as well, and you can see my project as the instance.

https://github.com/John-Lluch/SWRevealViewController

**Comment by PanosSakkos** [comment]
Found [this](https://www.youtube.com/watch?v=8EFfPT3UeWs) great tutorial.

Do you want to add it as a documentation in the project folder? it will be useful for anyone interested in the SWRevealViewController lirabry 😉 

Thanks!
:panos
