### ISSUE TITLE
Your article write very well， May I get your contact information

### ISSUE THREAD

**Issue by guodongZhao** [allenwong/30DaysofSwift#44]
# If inscribe！！
=========== 
Is my contact way：
     QQ: 742955968     Attention  ：Attach your name 
     Email :   [[742955968@qq.com](742955968@qq.com)]    OR   [15210075149@163.com](15210075149@163.com) 
     Tel ： China  By The iPhone    010-15210075149 
     Address : I live in Beijing haidian district
Thank you very much for your support
                                                ths！

**Comment by allenwong** [comment]
Wechat: AppKitchen

**Comment by guodongZhao** [comment]
freelanceseve




发自赵国栋
在2016年06月08日 12:20，Allen Wang 写道:

Wechat: AppKitchen
