### ISSUE TITLE
Project 06: Ambiguous reference to member '+'

### ISSUE THREAD

**Issue by DRiNVAD3R** [allenwong/30DaysofSwift#57]
Hello, I get the error:
**Ambiguous reference to member '+'**
at this:
            _self.locationLabel.text = locality! + postalCode! + administrativeArea! + country!_
any way to fix it?
I am just getting started with swift so I am not sure what the problem here is :/

EDIT: 
The problem seems to be with the **+ administrativeArea! + country!**, part I converted to swift 3.

**Comment by DRiNVAD3R** [comment]
change 

`self.locationLabel.text = locality! + postalCode! + administrativeArea! + country!`

with

```
self.locationLabel.text = postalCode! + " " + locality!
self.locationLabel.text?.append("\n" + administrativeArea! + ", " + country!)
```

**Comment by allenwong** [comment]
Thanks a lot! I merged that!
