### ISSUE TITLE
不支持 Swift3 ?

### ISSUE THREAD

**Issue by Huang-Libo** [allenwong/30DaysofSwift#59]
demo 在 Xcode 8.2 上提示需要转换为 Swift3

**Comment by allenwong** [comment]
https://github.com/allenwong/30DaysofSwift/tree/Swift-3

**Comment by Huang-Libo** [comment]
棒棒哒! 为何没有把 Swift3 分支放在主分支做呢?

**Comment by allenwong** [comment]
因为没有全部完善！我还是比较推荐这个基于此项目完善的。
https://github.com/soapyigu/Swift30Projects

**Comment by jijiucheng** [comment]
https://github.com/allenwong/30DaysofSwift/tree/Swift-3
这个链接，SourceTree 无法克隆呀！！！  大大！！！
一直提示是个无效的路径！！！

**Comment by jijiucheng** [comment]
https://github.com/allenwong/30DaysofSwift/tree/Swift-3
使用这个git链接无法克隆；如果还使用原来的链接，则是无法兼容 Swift 3.0；
求解呀，怎么样才能克隆呢

**Comment by jijiucheng** [comment]
话说 第10个demo ，占用内存好大呀！！直接 115MB+

**Comment by Huang-Libo** [comment]
Xcode 8.3.2 在 Swift 3 分支运行第一个项目报错
