### ISSUE TITLE
作者是不是放弃本项目了?

### ISSUE THREAD

**Issue by xiaomoinfo** [allenwong/30DaysofSwift#63]
都快1年了,版本也没更过。提的PR也不处理

**Comment by lydasia** [comment]
"30DaysofSwift"

[https://www.v2ex.com/t/256679](url)

**Comment by allenwong** [comment]
就是个学习项目，想要更多持续 Swift 学习，Google 和 YouTube 是最好的老师。
我主要在做新的真实项目。
